import { BarChart3, CreditCard, Headphones, PlusCircle, ShieldAlert, Trash2, Users } from "lucide-react";
import { PageShell } from "@/components/sections/page-shell";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { ownerRoomPolicies } from "@/lib/mock-data";

const metrics = [{ label: "Revenue", value: "₹8.4L", icon: CreditCard }, { label: "Participants", value: "18,420", icon: Users }, { label: "Engagement", value: "72%", icon: BarChart3 }, { label: "Reports", value: "14", icon: ShieldAlert }];
export default function OrganizerPage() {
  return <PageShell eyebrow="Organizer Dashboard" title="Run temporary ID-pass groups, payments, and Discord helpdesks from one console." description="Owners can create scrims, require roster login through a join link, unlock payment only when eligible, share ID-passwords in one-time groups, and delete rooms after completion."><div className="grid gap-5 lg:grid-cols-4">{metrics.map(({ label, value, icon: Icon }) => <Card key={label} className="p-5"><Icon className="text-arena-green" /><p className="mt-4 text-sm text-white/50">{label}</p><b className="font-display text-3xl">{value}</b></Card>)}</div><div className="mt-8 grid gap-6 lg:grid-cols-[1.2fr_.8fr]"><Card className="p-6"><div className="flex items-center justify-between"><h2 className="text-2xl font-black">Create center</h2><Button size="sm"><PlusCircle size={16} /> New event</Button></div><div className="mt-6 grid gap-4 sm:grid-cols-2"><Action title="Create Scrim" desc="Set game, fee, slot count, registration deadline, required team size, and group join link." /><Action title="Open ID-Pass Group" desc="Create an owner-controlled one-time group for ID-password drops and match announcements." /><Action title="Verify Roster Login" desc="Confirm each player joined with matching IGN, UID, and phone before paid checkout unlocks." /><Action title="Discord VC Helpdesk" desc="Attach the owner Discord voice channel for no-shows, rule disputes, and urgent support." /></div></Card><Card className="p-6"><h2 className="text-2xl font-black">Room lifecycle</h2><div className="mt-6 space-y-4">{ownerRoomPolicies.map((policy, index) => <div key={policy.title} className="flex gap-3 rounded-2xl border border-white/10 bg-black/25 p-4"><span className="grid h-10 w-10 place-items-center rounded-xl bg-arena-green/10 text-arena-green">{index === 1 ? <Trash2 size={18} /> : index === 3 ? <Headphones size={18} /> : index + 1}</span><div><h3 className="font-black">{policy.title}</h3><p className="mt-1 text-sm leading-6 text-white/55">{policy.description}</p></div></div>)}</div></Card></div><Card className="mt-8 p-6"><h2 className="text-2xl font-black">Revenue overview</h2><div className="mt-7 flex h-64 items-end gap-3">{[42, 68, 55, 88, 74, 96, 82].map((h, i) => <div key={i} className="flex-1 rounded-t-2xl bg-gradient-to-t from-arena-green to-arena-lime" style={{ height: `${h}%` }} />)}</div><p className="mt-4 text-sm text-white/50">Paid scrim checkout activates only after registration is open and the full roster has joined the organizer group link.</p></Card></PageShell>;
}
function Action({ title, desc }: { title: string; desc: string }) { return <div className="rounded-2xl border border-white/10 bg-black/25 p-5"><h3 className="font-black text-arena-green">{title}</h3><p className="mt-2 text-sm leading-6 text-white/55">{desc}</p></div>; }
