import { BarChart3, CreditCard, PlusCircle, ShieldAlert, Users } from "lucide-react";
import { PageShell } from "@/components/sections/page-shell";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";

const metrics = [{ label: "Revenue", value: "₹8.4L", icon: CreditCard }, { label: "Participants", value: "18,420", icon: Users }, { label: "Engagement", value: "72%", icon: BarChart3 }, { label: "Reports", value: "14", icon: ShieldAlert }];
export default function OrganizerPage() {
  return <PageShell eyebrow="Organizer Dashboard" title="Operate scrims and tournaments like a pro league." description="A Firebase-ready organizer workspace for creation flows, participant management, payment tracking, analytics, and moderation."><div className="grid gap-5 lg:grid-cols-4">{metrics.map(({ label, value, icon: Icon }) => <Card key={label} className="p-5"><Icon className="text-arena-cyan" /><p className="mt-4 text-sm text-white/50">{label}</p><b className="font-display text-3xl">{value}</b></Card>)}</div><div className="mt-8 grid gap-6 lg:grid-cols-[1.2fr_.8fr]"><Card className="p-6"><div className="flex items-center justify-between"><h2 className="text-2xl font-black">Create center</h2><Button size="sm"><PlusCircle size={16} /> New event</Button></div><div className="mt-6 grid gap-4 sm:grid-cols-2"><Action title="Create Scrim" desc="Set game, map pool, fee, slots, check-in, and Discord sync." /><Action title="Create Tournament" desc="Configure brackets, registration windows, payouts, rules, and streams." /><Action title="Manage Participants" desc="Approve teams, seed brackets, message captains, and export CSVs." /><Action title="Moderation Controls" desc="Handle disputes, no-shows, scam reports, and organizer trust impact." /></div></Card><Card className="p-6"><h2 className="text-2xl font-black">Revenue overview</h2><div className="mt-7 flex h-64 items-end gap-3">{[42, 68, 55, 88, 74, 96, 82].map((h, i) => <div key={i} className="flex-1 rounded-t-2xl bg-gradient-to-t from-arena-purple to-arena-cyan" style={{ height: `${h}%` }} />)}</div><p className="mt-4 text-sm text-white/50">Entry fees, sponsor boosts, wallet payouts, and refund tracking.</p></Card></div></PageShell>;
}
function Action({ title, desc }: { title: string; desc: string }) { return <div className="rounded-2xl border border-white/10 bg-black/25 p-5"><h3 className="font-black">{title}</h3><p className="mt-2 text-sm leading-6 text-white/55">{desc}</p></div>; }
