import { Award, Crosshair, Flame, Phone, ShieldCheck, Smartphone, Star } from "lucide-react";
import type { ReactNode } from "react";
import { PageShell } from "@/components/sections/page-shell";
import { Badge } from "@/components/ui/badge";
import { Card } from "@/components/ui/card";
import { profile } from "@/lib/mock-data";

export default function ProfilePage() {
  return <PageShell eyebrow="Player Profile" title="One verified esports identity for every scrim and tournament." description="TRXN keeps every player tied to the same IGN, UID, and active phone number so organizers can resolve no-shows, rule violations, and roster disputes quickly."><div className="grid gap-6 lg:grid-cols-[.8fr_1.2fr]"><Card className="p-6"><div className="grid h-28 w-28 place-items-center rounded-3xl bg-gradient-to-br from-arena-green to-arena-lime font-display text-4xl font-black text-black">RF</div><h2 className="mt-5 text-3xl font-black">{profile.handle}</h2><p className="text-arena-green">{profile.role}</p><p className="mt-2 text-white/55">{profile.rank}</p><div className="mt-6"><div className="flex justify-between text-sm"><span>Reputation Score</span><b>{profile.reputation}/100</b></div><div className="mt-2 h-3 rounded-full bg-white/10"><div className="h-full rounded-full bg-gradient-to-r from-arena-green to-arena-lime" style={{ width: `${profile.reputation}%` }} /></div></div><div className="mt-5 flex flex-wrap gap-2">{profile.badges.map((b) => <Badge key={b}>{b}</Badge>)}</div></Card><div className="grid gap-6"><Card className="p-6"><div className="flex items-center justify-between"><h3 className="text-xl font-black">Registered identity vault</h3><Badge className="border-arena-green/40 bg-arena-green/10 text-arena-green"><ShieldCheck size={14} /> Verified</Badge></div><div className="mt-5 grid gap-4 sm:grid-cols-3"><Identity icon={<ShieldCheck />} label="Same IGN" value={profile.ign} /><Identity icon={<Smartphone />} label="Game UID" value={profile.uid} /><Identity icon={<Phone />} label="Active phone" value={profile.phone} /></div><p className="mt-4 text-sm leading-6 text-white/55">This identity is reused across free and paid scrims, temporary owner groups, payment eligibility, Discord VC helpdesk checks, and moderation reports.</p></Card><Card className="p-6"><h3 className="text-xl font-black">Skill progression</h3><div className="mt-6 grid gap-4 sm:grid-cols-4">{["Aim", "IGL", "Utility", "Clutch"].map((s, i) => <div key={s} className="rounded-2xl border border-white/10 bg-black/25 p-4"><Crosshair className="text-arena-green" /><p className="mt-3 text-sm text-white/50">{s}</p><b>{88 - i * 6}%</b></div>)}</div></Card><Card className="p-6"><h3 className="text-xl font-black">Match history</h3>{["Won Genesis qualifier", "Top 3 BGMI Nightfall", "MVP in Spike Factory scrim"].map((m, i) => <div key={m} className="mt-4 flex items-center gap-4 rounded-2xl bg-white/5 p-4"><span className="grid h-10 w-10 place-items-center rounded-xl bg-white/10">{i === 0 ? <Award /> : i === 1 ? <Star /> : <Flame />}</span><span>{m}</span></div>)}</Card></div></div></PageShell>;
}

function Identity({ icon, label, value }: { icon: ReactNode; label: string; value: string }) { return <div className="rounded-2xl border border-arena-green/20 bg-arena-green/10 p-4"><span className="text-arena-green">{icon}</span><p className="mt-3 text-xs uppercase tracking-widest text-white/45">{label}</p><b>{value}</b></div>; }
